services:
  postgres:
    image: postgres:latest
    container_name: library-reservation-db
    environment:
      POSTGRES_DB: "library_reservation_db"
      POSTGRES_USER: "murat"
      POSTGRES_PASSWORD: "omerilebitirmeprojesi"
    ports:
      - "5432:5432"
    volumes:
      - /Users/muratertik/Desktop/volumes/library_db:/var/lib/postgresql