spring:
  application:
    name: KouLibraryReservationApp

  #datasouce conf start

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  #datasouce conf end

  #jpa conf start

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      org.hibernate:
        envers:
          global_with_modified_flag: true
      hibernate:

        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          #time_zone: UTC
          batch_size: 5
        order_updates: true
        order_inserts: true

    defer-datasource-initialization: false

  task:
    scheduling:
      pool:
        size: 2

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/kou-library
  #jpa conf end


keycloak:
  auth-server-url: http://localhost:8081
  realm: kou-library
  client-id: library-backend
  client-secret: ${KEYCLOAK_SECRET}