spring:
  application:
    name: KouLibraryReservationApp

  #datasouce conf start

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  #datasouce conf end

  #jpa conf start

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      org.hibernate:
        envers:
          global_with_modified_flag: true
      hibernate:

        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          #time_zone: UTC
          batch_size: 5
        order_updates: true
        order_inserts: true

    defer-datasource-initialization: false

  task:
    scheduling:
      pool:
        size: 2

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8081/realms/kou-library}

  #jpa conf end
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com


keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8081}
  realm: kou-library
  client-id: library-backend
  client-secret: ${KEYCLOAK_SECRET}

app:
  allowed-email-domain: ${ALLOWED_EMAIL_DOMAIN:kocaeli.edu.tr}

  qr:
    checkin-base-url: ${QR_CHECKIN_BASE_URL:http://localhost:5173/check-in}