
ALTER TABLE saloon_time_slots
    ALTER COLUMN start_time TYPE TIME WITHOUT TIME ZONE,
    ALTER COLUMN end_time   TYPE TIME WITHOUT TIME ZONE;

ALTER TABLE saloon_working_hours
    ALTER COLUMN opening_time TYPE TIME WITHOUT TIME ZONE,
    ALTER COLUMN closing_time TYPE TIME WITHOUT TIME ZONE;

ALTER TABLE library_working_hours
    ALTER COLUMN opening_time TYPE TIME WITHOUT TIME ZONE,
    ALTER COLUMN closing_time TYPE TIME WITHOUT TIME ZONE;

ALTER TABLE saloon_closures
    ALTER COLUMN start_date_time TYPE TIMESTAMP WITHOUT TIME ZONE,
    ALTER COLUMN end_date_time   TYPE TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE library_closures
    ALTER COLUMN start_date_time TYPE TIMESTAMP WITHOUT TIME ZONE,
    ALTER COLUMN end_date_time   TYPE TIMESTAMP WITHOUT TIME ZONE;