CREATE TABLE verification_codes (
                                    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    user_id     BIGINT NOT NULL REFERENCES users(id),
                                    code        VARCHAR(6) NOT NULL,
                                    type        VARCHAR(40) NOT NULL,
                                    expires_at  TIMESTAMP NOT NULL,
                                    consumed_at TIMESTAMP,
                                    created_at  TIMESTAMP NOT NULL
);
CREATE INDEX idx_verification_user_type ON verification_codes (user_id, type);